### ISSUE TITLE
using cURL 7.43 - an error occurs

### ISSUE THREAD

**Issue by 2cent2** [Lanjelin/hue-batch#2]
Hi and thanks for your efforts!

Unfortunately I not finding a cURL version 7.37.0 so I have used the latest one and I am getting an error while running the batch with cURL v7.43.0.

It states:
C:\temp>hue.bat -k alonglongID -l "1" -on true -h 25500 -s 212
curl: (3) [globbing] unmatched close brace/bracket in column 19

curl: (3) [globbing] unmatched close brace/bracket in column 19

curl: (3) [globbing] unmatched close brace/bracket in column 19

Any help would be appreciated.

Thanks,
Martin

**Comment by 2cent2** [comment]
got it working by addning the ip manually to the _hueip variable.

**Comment by Lanjelin** [comment]
Hi there, thanks for making me aware.

Didn't have the old cURL version myself to compare, and thus I'm a bit uncertain wether this is related to cURL or the address where it gets your IP.

Anyways, I've updated the code now to work fine getting the IP automagically, using the newest (7.43.0) version of cURL.

Cheers,
Lanjelin

**Comment by 2cent2** [comment]
Wohoo,

excellent - just downloaded and tested.
It´s working fine for me.


Thanks a lot,
Martin
