### ISSUE TITLE
Lookup page changed

### ISSUE THREAD

**Issue by GibStorm** [Lanjelin/hue-batch#6]
Today, my scripts wouldn't work. After some investigating, it seems that Philips has changed the bridge lookup URL.

I changed 'https://www.meethue.com/api/nupnp' to 'https://discovery.meethue.com'  in the hue.bat file, and then everything worked again.

**Comment by Lanjelin** [comment]
Thanks for informing me, seems all the urls where outdated.
Updated the .bat
